// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SourcingOps.Infrastructure.Persistence;

#nullable disable

namespace SourcingOps.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727084330_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SourcingOps.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("EntityId")
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_audit_logs_entity_type");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_logs_occurred_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.CatalogDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CatalogSectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_section_id");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("boolean")
                        .HasColumnName("is_latest");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_filename");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<string>("VersionLabel")
                        .HasColumnType("text")
                        .HasColumnName("version_label");

                    b.HasKey("Id")
                        .HasName("pk_catalog_documents");

                    b.HasIndex("CatalogSectionId")
                        .HasDatabaseName("ix_catalog_documents_catalog_section_id");

                    b.HasIndex("IsLatest")
                        .HasDatabaseName("ix_catalog_documents_is_latest");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("ix_catalog_documents_uploaded_at");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_catalog_documents_uploaded_by_user_id");

                    b.ToTable("catalog_documents", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.CatalogSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_catalog_sections");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_catalog_sections_category_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_catalog_sections_title");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_catalog_sections_vendor_id");

                    b.ToTable("catalog_sections", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_categories_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessName")
                        .HasColumnType("text")
                        .HasColumnName("business_name");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ExternalPurchaseReference")
                        .HasColumnType("text")
                        .HasColumnName("external_purchase_reference");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_type_id");

                    b.Property<string>("SourceChannel")
                        .HasColumnType("text")
                        .HasColumnName("source_channel");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_customers_created_at");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_customers_owner_user_id");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_customers_phone");

                    b.HasIndex("ServiceTypeId")
                        .HasDatabaseName("ix_customers_service_type_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_customers_status_id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.CustomerCategory", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("CustomerId", "CategoryId")
                        .HasName("pk_customer_categories");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_customer_categories_category_id");

                    b.ToTable("customer_categories", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Dispatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CatalogDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_document_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("StaffUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_user_id");

                    b.HasKey("Id")
                        .HasName("pk_dispatches");

                    b.HasIndex("CatalogDocumentId")
                        .HasDatabaseName("ix_dispatches_catalog_document_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_dispatches_customer_id");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("ix_dispatches_sent_at");

                    b.HasIndex("StaffUserId")
                        .HasDatabaseName("ix_dispatches_staff_user_id");

                    b.ToTable("dispatches", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Interaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("FollowUpDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("follow_up_date");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_interactions");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_interactions_author_user_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_interactions_created_at");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_interactions_customer_id");

                    b.HasIndex("FollowUpDate")
                        .HasDatabaseName("ix_interactions_follow_up_date");

                    b.ToTable("interactions", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<decimal>("OnHandQty")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("on_hand_qty");

                    b.Property<decimal>("ReorderThreshold")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("reorder_threshold");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_items");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_inventory_items_category_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_inventory_items_name");

                    b.HasIndex("Sku")
                        .HasDatabaseName("ix_inventory_items_sku");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_inventory_items_vendor_id");

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_number");

                    b.Property<string>("LineDescription")
                        .HasColumnType("text")
                        .HasColumnName("line_description");

                    b.Property<string>("PdfFilePath")
                        .HasColumnType("text")
                        .HasColumnName("pdf_file_path");

                    b.Property<Guid?>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_amount");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_invoices_created_by_user_id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_invoices_customer_id");

                    b.HasIndex("InvoiceDate")
                        .HasDatabaseName("ix_invoices_invoice_date");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_invoice_number");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("ix_invoices_shipment_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_invoices_status_id");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.InvoiceStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_invoice_statuses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_invoice_statuses_code");

                    b.ToTable("invoice_statuses", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.LeadStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_lead_statuses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_lead_statuses_code");

                    b.ToTable("lead_statuses", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_code");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.ServiceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_service_types");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_service_types_code");

                    b.ToTable("service_types", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AwbOrBl")
                        .HasColumnType("text")
                        .HasColumnName("awb_or_bl");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Destination")
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<DateTime?>("DispatchDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatch_date");

                    b.Property<DateTime?>("Eta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eta");

                    b.Property<decimal?>("FreightCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("freight_cost");

                    b.Property<string>("Mode")
                        .HasColumnType("text")
                        .HasColumnName("mode");

                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_type_id");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<decimal?>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_value");

                    b.HasKey("Id")
                        .HasName("pk_shipments");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_shipments_created_at");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_shipments_customer_id");

                    b.HasIndex("DispatchDate")
                        .HasDatabaseName("ix_shipments_dispatch_date");

                    b.HasIndex("ServiceTypeId")
                        .HasDatabaseName("ix_shipments_service_type_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_shipments_status_id");

                    b.ToTable("shipments", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.ShipmentDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("doc_type");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_filename");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_shipment_documents");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("ix_shipment_documents_shipment_id");

                    b.ToTable("shipment_documents", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.ShipmentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("shipment_id");

                    b.HasKey("Id")
                        .HasName("pk_shipment_lines");

                    b.HasIndex("InventoryItemId")
                        .HasDatabaseName("ix_shipment_lines_inventory_item_id");

                    b.HasIndex("ShipmentId")
                        .HasDatabaseName("ix_shipment_lines_shipment_id");

                    b.ToTable("shipment_lines", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.ShipmentStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_shipment_statuses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_shipment_statuses_code");

                    b.ToTable("shipment_statuses", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_users_is_active");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text")
                        .HasColumnName("contact_person");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("LeadTime")
                        .HasColumnType("text")
                        .HasColumnName("lead_time");

                    b.Property<string>("Moq")
                        .HasColumnType("text")
                        .HasColumnName("moq");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Region")
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<decimal?>("ReliabilityRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("reliability_rating");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.HasKey("Id")
                        .HasName("pk_vendors");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_vendors_name");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_vendors_status_id");

                    b.ToTable("vendors", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.VendorCategory", b =>
                {
                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("VendorId", "CategoryId")
                        .HasName("pk_vendor_categories");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_vendor_categories_category_id");

                    b.ToTable("vendor_categories", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.VendorStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_vendor_statuses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_vendor_statuses_code");

                    b.ToTable("vendor_statuses", (string)null);
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("SourcingOps.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_audit_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.CatalogDocument", b =>
                {
                    b.HasOne("SourcingOps.Domain.Entities.CatalogSection", "CatalogSection")
                        .WithMany("Documents")
                        .HasForeignKey("CatalogSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_documents_catalog_sections_catalog_section_id");

                    b.HasOne("SourcingOps.Domain.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_documents_users_uploaded_by_user_id");

                    b.Navigation("CatalogSection");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.CatalogSection", b =>
                {
                    b.HasOne("SourcingOps.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_sections_categories_category_id");

                    b.HasOne("SourcingOps.Domain.Entities.Vendor", "Vendor")
                        .WithMany("CatalogSections")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_catalog_sections_vendors_vendor_id");

                    b.Navigation("Category");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Customer", b =>
                {
                    b.HasOne("SourcingOps.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_customers_users_owner_user_id");

                    b.HasOne("SourcingOps.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customers_service_types_service_type_id");

                    b.HasOne("SourcingOps.Domain.Entities.LeadStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customers_lead_statuses_status_id");

                    b.Navigation("Owner");

                    b.Navigation("ServiceType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.CustomerCategory", b =>
                {
                    b.HasOne("SourcingOps.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_categories_categories_category_id");

                    b.HasOne("SourcingOps.Domain.Entities.Customer", "Customer")
                        .WithMany("CustomerCategories")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_categories_customers_customer_id");

                    b.Navigation("Category");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Dispatch", b =>
                {
                    b.HasOne("SourcingOps.Domain.Entities.CatalogDocument", "CatalogDocument")
                        .WithMany("Dispatches")
                        .HasForeignKey("CatalogDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dispatches_catalog_documents_catalog_document_id");

                    b.HasOne("SourcingOps.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dispatches_customers_customer_id");

                    b.HasOne("SourcingOps.Domain.Entities.User", "StaffUser")
                        .WithMany()
                        .HasForeignKey("StaffUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dispatches_users_staff_user_id");

                    b.Navigation("CatalogDocument");

                    b.Navigation("Customer");

                    b.Navigation("StaffUser");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Interaction", b =>
                {
                    b.HasOne("SourcingOps.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_interactions_users_author_user_id");

                    b.HasOne("SourcingOps.Domain.Entities.Customer", "Customer")
                        .WithMany("Interactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interactions_customers_customer_id");

                    b.Navigation("Author");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.InventoryItem", b =>
                {
                    b.HasOne("SourcingOps.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_items_categories_category_id");

                    b.HasOne("SourcingOps.Domain.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_inventory_items_vendors_vendor_id");

                    b.Navigation("Category");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("SourcingOps.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_users_created_by_user_id");

                    b.HasOne("SourcingOps.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_customers_customer_id");

                    b.HasOne("SourcingOps.Domain.Entities.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_invoices_shipments_shipment_id");

                    b.HasOne("SourcingOps.Domain.Entities.InvoiceStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_invoice_statuses_status_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Customer");

                    b.Navigation("Shipment");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SourcingOps.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("SourcingOps.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("SourcingOps.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("SourcingOps.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shipments_customers_customer_id");

                    b.HasOne("SourcingOps.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shipments_service_types_service_type_id");

                    b.HasOne("SourcingOps.Domain.Entities.ShipmentStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shipments_shipment_statuses_status_id");

                    b.Navigation("Customer");

                    b.Navigation("ServiceType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.ShipmentDocument", b =>
                {
                    b.HasOne("SourcingOps.Domain.Entities.Shipment", "Shipment")
                        .WithMany("Documents")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shipment_documents_shipments_shipment_id");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.ShipmentLine", b =>
                {
                    b.HasOne("SourcingOps.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithMany("ShipmentLines")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shipment_lines_inventory_items_inventory_item_id");

                    b.HasOne("SourcingOps.Domain.Entities.Shipment", "Shipment")
                        .WithMany("Lines")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shipment_lines_shipments_shipment_id");

                    b.Navigation("InventoryItem");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("SourcingOps.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("SourcingOps.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Vendor", b =>
                {
                    b.HasOne("SourcingOps.Domain.Entities.VendorStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendors_vendor_statuses_status_id");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.VendorCategory", b =>
                {
                    b.HasOne("SourcingOps.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_categories_categories_category_id");

                    b.HasOne("SourcingOps.Domain.Entities.Vendor", "Vendor")
                        .WithMany("VendorCategories")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_categories_vendors_vendor_id");

                    b.Navigation("Category");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.CatalogDocument", b =>
                {
                    b.Navigation("Dispatches");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.CatalogSection", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Customer", b =>
                {
                    b.Navigation("CustomerCategories");

                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.InventoryItem", b =>
                {
                    b.Navigation("ShipmentLines");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Shipment", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SourcingOps.Domain.Entities.Vendor", b =>
                {
                    b.Navigation("CatalogSections");

                    b.Navigation("VendorCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
